server:
  port: 9091

spring:
  datasource:
    username: sa
    password: pwd
    url: jdbc:h2:file:./db/demodb;MODE=PostgreSQL
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
