server:
  port: 9091

spring:
  datasource:
    username: sa
    password: pwd
    url: jdbc:h2:file:./db/demodb;MODE=PostgreSQL
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

#  liquibase:
#    enabled: true #Default value
#    change-log: classpath:/db.changelog/db.changelog-master.yaml #Default value

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
